platform :ios, '7.0'
#use_frameworks!
target 'TemplateTest' do
pod 'AFNetworking', '~> 2.0'
pod 'SDWebImage', '~> 3.7.2'
pod 'UMengSocial', '>= 4.3'
pod 'UMengFeedback', '>= 2.2'
pod 'UMengAnalytics', '>= 3.4.6'
pod 'AMap3DMap', '~> 5.0.0'
pod 'AMapSearch', '~> 5.0.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'PureLayout', '~> 2.0.5'
pod 'ReactiveViewModel', '~> 0.3'
pod 'libextobjc', '~> 0.4.1'
pod 'ReactiveCocoa', '2.5'
pod 'HMSegmentedControl', '~> 1.5.2'
pod 'iCarousel', '~> 1.8.2'
pod 'IQKeyboardManager', '3.3.4'
pod 'pop', '~> 1.0.8'
pod 'AsyncDisplayKit', '1.9.3'
pod 'MagicalRecord', '~> 2.3.2'
pod 'YYImage', '~> 1.0.2'
pod 'YYCategories', '~> 1.0.4'
pod 'YYModel', '~> 1.0.4'
pod 'YYText', '~> 1.0.7'
pod 'MJRefresh', '~> 3.1.12'
pod 'JPush', '~> 3.0.6'
end
